// @ts-nocheck
// C ref: nethack-c-v5/upstream/src/cmd.c `struct ext_func_tab extcmdlist[]` (170 entries),
// in C declaration order — commands_init() (cmd.c:3419) walks the table in this
// order and cmdbind_add() (cmd.c:2795) PREPENDS to gc.Cmd.cmdbinds, so the order
// here determines the scan order cmd_from_func() (cmd.c:3705) resolves against.
// `key` is the uchar ef_key with C()/M() already applied (hack.h: C(c)=0x1f&c,
// M(c)=0x80|c); 0 means "no default binding".  `desc` is ef_desc and `flags` is
// the ef_flags word (bit values from include/func_tab.h).
export const EXTCMDLIST = [
    { key: 35, name: "#", desc: "enter and perform an extended command", func: "doextcmd", flags: 137 },
    { key: 191, name: "?", desc: "list all extended commands", func: "doextlist", flags: 139 },
    { key: 225, name: "adjust", desc: "adjust inventory letters", func: "doorganize", flags: 11 },
    { key: 193, name: "annotate", desc: "name current level", func: "donamelevel", flags: 139 },
    { key: 97, name: "apply", desc: "apply (use) a tool (pick-axe, key, lamp...)", func: "doapply", flags: 128 },
    { key: 24, name: "attributes", desc: "show your attributes", func: "doattributes", flags: 9 },
    { key: 64, name: "autopickup", desc: "toggle the 'autopickup' option on/off", func: "dotogglepickup", flags: 9 },
    { key: 0, name: "bugreport", desc: "file a bug report", func: "dobugreport", flags: 40 },
    { key: 67, name: "call", desc: "name a monster, specific object, or type of object", func: "docallcmd", flags: 9 },
    { key: 90, name: "cast", desc: "zap (cast) a spell", func: "docast", flags: 1 },
    { key: 227, name: "chat", desc: "talk to someone", func: "dotalk", flags: 3 },
    { key: 118, name: "chronicle", desc: "show journal of major events", func: "do_gamelog", flags: 11 },
    { key: 99, name: "close", desc: "close a door", func: "doclose", flags: 0 },
    { key: 195, name: "conduct", desc: "list voluntary challenges you have maintained", func: "doconduct", flags: 11 },
    { key: 0, name: "debugfuzzer", desc: "start the fuzz tester", func: "wiz_fuzzer", flags: 37 },
    { key: 228, name: "dip", desc: "dip an object into something", func: "dodip", flags: 130 },
    { key: 62, name: "down", desc: "go down a staircase", func: "dodown", flags: 128 },
    { key: 100, name: "drop", desc: "drop an item", func: "dodrop", flags: 0 },
    { key: 68, name: "droptype", desc: "drop specific item types", func: "doddrop", flags: 0 },
    { key: 101, name: "eat", desc: "eat something", func: "doeat", flags: 128 },
    { key: 69, name: "engrave", desc: "engrave writing on the floor", func: "doengrave", flags: 0 },
    { key: 229, name: "enhance", desc: "advance or check weapon and spell skills", func: "enhance_weapon_skill", flags: 11 },
    { key: 216, name: "exploremode", desc: "enter explore (discovery) mode", func: "enter_explore_mode", flags: 41 },
    { key: 70, name: "fight", desc: "prefix: force fight even if you don't see a monster", func: "do_fight", flags: 512 },
    { key: 102, name: "fire", desc: "fire ammunition from quiver", func: "dofire", flags: 0 },
    { key: 230, name: "force", desc: "force a lock", func: "doforce", flags: 2 },
    { key: 231, name: "genocided", desc: "list monsters that have been genocided or become extinct", func: "dogenocided", flags: 139 },
    { key: 59, name: "glance", desc: "show what type of thing a map symbol corresponds to", func: "doquickwhatis", flags: 9 },
    { key: 63, name: "help", desc: "give a help message", func: "dohelp", flags: 9 },
    { key: 0, name: "herecmdmenu", desc: "show menu of commands you can do here", func: "doherecmdmenu", flags: 11 },
    { key: 0, name: "history", desc: "show a summary of the game's development", func: "dohistory", flags: 11 },
    { key: 105, name: "inventory", desc: "show your inventory", func: "ddoinv", flags: 9 },
    { key: 73, name: "inventtype", desc: "show inventory of one specific item class", func: "dotypeinv", flags: 9 },
    { key: 233, name: "invoke", desc: "invoke an object's special powers", func: "doinvoke", flags: 3 },
    { key: 234, name: "jump", desc: "jump to another location", func: "dojump", flags: 2 },
    { key: 4, name: "kick", desc: "kick something", func: "dokick", flags: 0 },
    { key: 92, name: "known", desc: "show what object types have been discovered", func: "dodiscovered", flags: 137 },
    { key: 96, name: "knownclass", desc: "show discovered types for one class of objects", func: "doclassdisco", flags: 137 },
    { key: 0, name: "levelchange", desc: "change experience level", func: "wiz_level_change", flags: 7 },
    { key: 0, name: "lightsources", desc: "show mobile light sources", func: "wiz_light_sources", flags: 7 },
    { key: 58, name: "look", desc: "look at what is here", func: "dolook", flags: 1 },
    { key: 0, name: "lookaround", desc: "describe what you can see", func: "dolookaround", flags: 9 },
    { key: 236, name: "loot", desc: "loot a box on the floor", func: "doloot", flags: 130 },
    { key: 0, name: "migratemons", desc: "show migrating monsters and migrate N random ones", func: "wiz_migrate_mons", flags: 7 },
    { key: 237, name: "monster", desc: "use monster's special ability", func: "domonability", flags: 3 },
    { key: 238, name: "name", desc: "same as call; name a monster or object or object type", func: "docallcmd", flags: 11 },
    { key: 239, name: "offer", desc: "offer a sacrifice to the gods", func: "dosacrifice", flags: 130 },
    { key: 111, name: "open", desc: "open a door", func: "doopen", flags: 0 },
    { key: 79, name: "options", desc: "show option settings", func: "doset_simple", flags: 137 },
    { key: 0, name: "optionsfull", desc: "show all option settings, possibly change them", func: "doset", flags: 137 },
    { key: 15, name: "overview", desc: "show a summary of the explored dungeon", func: "dooverview", flags: 139 },
    { key: 0, name: "panic", desc: "test panic routine (fatal to game)", func: "wiz_panic", flags: 7 },
    { key: 112, name: "pay", desc: "pay your shopping bill", func: "dopay", flags: 128 },
    { key: 124, name: "perminv", desc: "scroll persistent inventory display", func: "doperminv", flags: 41 },
    { key: 44, name: "pickup", desc: "pick up things at the current location", func: "dopickup", flags: 128 },
    { key: 0, name: "polyself", desc: "polymorph self", func: "wiz_polyself", flags: 7 },
    { key: 240, name: "pray", desc: "pray to the gods for help", func: "dopray", flags: 3 },
    { key: 16, name: "prevmsg", desc: "view recent game messages", func: "doprev_message", flags: 4105 },
    { key: 80, name: "puton", desc: "put on an accessory (ring, amulet, etc)", func: "doputon", flags: 0 },
    { key: 113, name: "quaff", desc: "quaff (drink) something", func: "dodrink", flags: 128 },
    { key: 0, name: "quit", desc: "exit without saving current game", func: "done2", flags: 43 },
    { key: 81, name: "quiver", desc: "select ammunition for quiver", func: "dowieldquiver", flags: 0 },
    { key: 114, name: "read", desc: "read a scroll or spellbook", func: "doread", flags: 0 },
    { key: 18, name: "redraw", desc: "redraw screen", func: "doredraw", flags: 4105 },
    { key: 82, name: "remove", desc: "remove an accessory (ring, amulet, etc)", func: "doremring", flags: 0 },
    { key: 1, name: "repeat", desc: "repeat a previous command", func: "do_repeat", flags: 9 },
    { key: 109, name: "reqmenu", desc: "prefix: request menu or modify command", func: "do_reqmenu", flags: 512 },
    { key: 31, name: "retravel", desc: "travel to previously selected travel location", func: "dotravel_target", flags: 0 },
    { key: 210, name: "ride", desc: "mount or dismount a saddled steed", func: "doride", flags: 2 },
    { key: 242, name: "rub", desc: "rub a lamp or a stone", func: "dorub", flags: 2 },
    { key: 71, name: "run", desc: "prefix: run until something interesting is seen", func: "do_run", flags: 512 },
    { key: 103, name: "rush", desc: "prefix: rush until something interesting is seen", func: "do_rush", flags: 512 },
    { key: 83, name: "save", desc: "save the game and exit", func: "dosave", flags: 41 },
    { key: 0, name: "saveoptions", desc: "save the game configuration", func: "do_write_config_file", flags: 41 },
    { key: 115, name: "search", desc: "search for traps and secret doors", func: "dosearch", flags: 129 },
    { key: 42, name: "seeall", desc: "show all equipment in use", func: "doprinuse", flags: 137 },
    { key: 34, name: "seeamulet", desc: "show the amulet currently worn", func: "dopramulet", flags: 137 },
    { key: 91, name: "seearmor", desc: "show the armor currently worn", func: "doprarm", flags: 137 },
    { key: 61, name: "seerings", desc: "show the ring(s) currently worn", func: "doprring", flags: 137 },
    { key: 40, name: "seetools", desc: "show the tools currently in use", func: "doprtool", flags: 137 },
    { key: 41, name: "seeweapon", desc: "show the weapon currently wielded", func: "doprwep", flags: 137 },
    { key: 33, name: "shell", desc: "leave game to enter a sub-shell ('exit' to come back)", func: "dosh_core", flags: 41 },
    { key: 36, name: "showgold", desc: "show gold, possibly shop credit or debt", func: "doprgold", flags: 137 },
    { key: 43, name: "showspells", desc: "list and reorder known spells", func: "dovspell", flags: 9 },
    { key: 94, name: "showtrap", desc: "describe an adjacent, discovered trap", func: "doidtrap", flags: 9 },
    { key: 243, name: "sit", desc: "sit down", func: "dosit", flags: 2 },
    { key: 0, name: "stats", desc: "show memory statistics", func: "wiz_show_stats", flags: 7 },
    { key: 26, name: "suspend", desc: "push game to background ('fg' to come back)", func: "dosuspend_core", flags: 41 },
    { key: 120, name: "swap", desc: "swap wielded and secondary weapons", func: "doswapweapon", flags: 0 },
    { key: 84, name: "takeoff", desc: "take off one piece of armor", func: "dotakeoff", flags: 0 },
    { key: 65, name: "takeoffall", desc: "remove all armor", func: "doddoremarm", flags: 0 },
    { key: 20, name: "teleport", desc: "teleport around the level", func: "dotelecmd", flags: 129 },
    { key: 127, name: "terrain", desc: "view map without monsters or objects obstructing it", func: "doterrain", flags: 11 },
    { key: 0, name: "therecmdmenu", desc: "menu of commands you can do from here to adjacent spot", func: "dotherecmdmenu", flags: 2058 },
    { key: 116, name: "throw", desc: "throw something", func: "dothrow", flags: 0 },
    { key: 0, name: "timeout", desc: "look at timeout queue and hero's timed intrinsics", func: "wiz_timeout_queue", flags: 7 },
    { key: 212, name: "tip", desc: "empty a container", func: "dotip", flags: 130 },
    { key: 0, name: "toggle", desc: "toggle boolean option", func: "dotoggleoption", flags: 16393 },
    { key: 95, name: "travel", desc: "travel to a specific location on the map", func: "dotravel", flags: 128 },
    { key: 244, name: "turn", desc: "turn undead away", func: "doturn", flags: 3 },
    { key: 88, name: "twoweapon", desc: "toggle two-weapon combat", func: "dotwoweapon", flags: 0 },
    { key: 245, name: "untrap", desc: "untrap something", func: "dountrap", flags: 2 },
    { key: 60, name: "up", desc: "go up a staircase", func: "doup", flags: 128 },
    { key: 214, name: "vanquished", desc: "list vanquished monsters", func: "dovanquished", flags: 139 },
    { key: 246, name: "version", desc: "list compile time options for this version of NetHack", func: "doextversion", flags: 11 },
    { key: 86, name: "versionshort", desc: "show version and date+time program was built", func: "doversion", flags: 137 },
    { key: 0, name: "vision", desc: "show vision array", func: "wiz_show_vision", flags: 7 },
    { key: 46, name: "wait", desc: "rest one move while doing nothing", func: "donull", flags: 129 },
    { key: 87, name: "wear", desc: "wear a piece of armor", func: "dowear", flags: 0 },
    { key: 38, name: "whatdoes", desc: "tell what a command does", func: "dowhatdoes", flags: 9 },
    { key: 47, name: "whatis", desc: "show what type of thing a symbol corresponds to", func: "dowhatis", flags: 9 },
    { key: 119, name: "wield", desc: "wield (put in use) a weapon", func: "dowield", flags: 0 },
    { key: 247, name: "wipe", desc: "wipe off your face", func: "dowipe", flags: 2 },
    { key: 0, name: "wizborn", desc: "show stats of monsters created", func: "doborn", flags: 5 },
    { key: 0, name: "wizbury", desc: "bury objs under and around you", func: "wiz_debug_cmd_bury", flags: 7 },
    { key: 0, name: "wizcast", desc: "cast any spell", func: "dowizcast", flags: 5 },
    { key: 0, name: "wizcustom", desc: "show customized glyphs", func: "wiz_custom", flags: 37 },
    { key: 5, name: "wizdetect", desc: "reveal hidden things within a small radius", func: "wiz_detect", flags: 5 },
    { key: 0, name: "wizdispmacros", desc: "validate the display macro ranges", func: "wiz_display_macros", flags: 7 },
    { key: 0, name: "wizfliplevel", desc: "flip the level", func: "wiz_flip_level", flags: 5 },
    { key: 7, name: "wizgenesis", desc: "create a monster", func: "wiz_genesis", flags: 5 },
    { key: 9, name: "wizidentify", desc: "identify all items in inventory", func: "wiz_identify", flags: 5 },
    { key: 0, name: "wizintrinsic", desc: "set an intrinsic", func: "wiz_intrinsic", flags: 7 },
    { key: 0, name: "wizkill", desc: "slay a monster", func: "wiz_kill", flags: 167 },
    { key: 22, name: "wizlevelport", desc: "teleport to another level", func: "wiz_level_tele", flags: 133 },
    { key: 0, name: "wizloaddes", desc: "load and execute a des-file lua script", func: "wiz_load_splua", flags: 37 },
    { key: 0, name: "wizloadlua", desc: "load and execute a lua script", func: "wiz_load_lua", flags: 37 },
    { key: 0, name: "wizobjprobs", desc: "list object generation probabilities", func: "wiz_objprobs", flags: 5 },
    { key: 0, name: "wizmakemap", desc: "recreate the current level", func: "wiz_makemap", flags: 5 },
    { key: 6, name: "wizmap", desc: "map the level", func: "wiz_map", flags: 5 },
    { key: 0, name: "wizmondiff", desc: "validate the difficulty ratings of monsters", func: "wiz_mon_diff", flags: 7 },
    { key: 0, name: "wizrumorcheck", desc: "verify rumor boundaries", func: "wiz_rumor_check", flags: 7 },
    { key: 0, name: "wizseenv", desc: "show map locations' seen vectors", func: "wiz_show_seenv", flags: 7 },
    { key: 0, name: "wizshownhuuid", desc: "show NHUUID for this game", func: "wiz_show_nhuuid", flags: 6 },
    { key: 0, name: "wizsmell", desc: "smell monster", func: "wiz_smell", flags: 7 },
    { key: 0, name: "wiztelekinesis", desc: "telekinesis", func: "wiz_telekinesis", flags: 7 },
    { key: 0, name: "wizwhere", desc: "show locations of special levels", func: "wiz_where", flags: 7 },
    { key: 23, name: "wizwish", desc: "wish for something", func: "wiz_wish", flags: 133 },
    { key: 0, name: "wmode", desc: "show wall modes", func: "wiz_show_wmodes", flags: 7 },
    { key: 122, name: "zap", desc: "zap a wand", func: "dozap", flags: 0 },
    { key: 0, name: "movewest", desc: "move west (screen left)", func: "do_move_west", flags: 1408 },
    { key: 0, name: "movenorthwest", desc: "move northwest (screen upper left)", func: "do_move_northwest", flags: 1408 },
    { key: 0, name: "movenorth", desc: "move north (screen up)", func: "do_move_north", flags: 1408 },
    { key: 0, name: "movenortheast", desc: "move northeast (screen upper right)", func: "do_move_northeast", flags: 1408 },
    { key: 0, name: "moveeast", desc: "move east (screen right)", func: "do_move_east", flags: 1408 },
    { key: 0, name: "movesoutheast", desc: "move southeast (screen lower right)", func: "do_move_southeast", flags: 1408 },
    { key: 0, name: "movesouth", desc: "move south (screen down)", func: "do_move_south", flags: 1408 },
    { key: 0, name: "movesouthwest", desc: "move southwest (screen lower left)", func: "do_move_southwest", flags: 1408 },
    { key: 0, name: "rushwest", desc: "rush west (screen left)", func: "do_rush_west", flags: 1152 },
    { key: 0, name: "rushnorthwest", desc: "rush northwest (screen upper left)", func: "do_rush_northwest", flags: 1152 },
    { key: 0, name: "rushnorth", desc: "rush north (screen up)", func: "do_rush_north", flags: 1152 },
    { key: 0, name: "rushnortheast", desc: "rush northeast (screen upper right)", func: "do_rush_northeast", flags: 1152 },
    { key: 0, name: "rusheast", desc: "rush east (screen right)", func: "do_rush_east", flags: 1152 },
    { key: 0, name: "rushsoutheast", desc: "rush southeast (screen lower right)", func: "do_rush_southeast", flags: 1152 },
    { key: 0, name: "rushsouth", desc: "rush south (screen down)", func: "do_rush_south", flags: 1152 },
    { key: 0, name: "rushsouthwest", desc: "rush southwest (screen lower left)", func: "do_rush_southwest", flags: 1152 },
    { key: 0, name: "runwest", desc: "run west (screen left)", func: "do_run_west", flags: 1152 },
    { key: 0, name: "runnorthwest", desc: "run northwest (screen upper left)", func: "do_run_northwest", flags: 1152 },
    { key: 0, name: "runnorth", desc: "run north (screen up)", func: "do_run_north", flags: 1152 },
    { key: 0, name: "runnortheast", desc: "run northeast (screen upper right)", func: "do_run_northeast", flags: 1152 },
    { key: 0, name: "runeast", desc: "run east (screen right)", func: "do_run_east", flags: 1152 },
    { key: 0, name: "runsoutheast", desc: "run southeast (screen lower right)", func: "do_run_southeast", flags: 1152 },
    { key: 0, name: "runsouth", desc: "run south (screen down)", func: "do_run_south", flags: 1152 },
    { key: 0, name: "runsouthwest", desc: "run southwest (screen lower left)", func: "do_run_southwest", flags: 1152 },
    { key: 0, name: "clicklook", desc: null, func: "doclicklook", flags: 2112, internal: true },
    { key: 0, name: "mouseaction", desc: null, func: "domouseaction", flags: 2112, internal: true },
    { key: 0, name: "altadjust", desc: null, func: "adjust_split", flags: 64, internal: true },
    { key: 0, name: "altdip", desc: null, func: "dip_into", flags: 64, internal: true },
    { key: 0, name: "alttakeoff", desc: null, func: "ia_dotakeoff", flags: 64, internal: true },
    { key: 0, name: "altunwield", desc: null, func: "remarm_swapwep", flags: 64, internal: true },
];
