// js/dat_source.js
// The ONE place the port resolves a `dat/<name>` file at runtime.
//
// WHY THIS EXISTS — TWO REASONS, AND THE SECOND ONE COST THE WHOLE SCORE
// ----------------------------------------------------------------------
// not have it.  The only tracked source of 5.0 dat content is `js/dat/`, and
// `V5_DIVERGENT` below is the guard, as data rather than as a comment, over
// the names where serving 3.7 would be serving the wrong bytes.
//
// (2) THE PORT MAY NOT TOUCH A FILESYSTEM AT ALL.  Upstream's README, "Rules":
//
//     "Submissions must be plain JavaScript.  ES6 modules, runnable as-is in
//      both Node 22+ and modern Chrome. ... No WASM, no internet or filesystem
//      or threads, no native addons."
//     "Sandboxed scoring.  Your code runs in a Node child process with
//      --permission and a minimal --allow-fs-read whitelist"
//
// This file used to hand its callers a PATH and let them read it.  That failed
//
// Reproduced exactly, two-sided, by hiding nethack-c/ from a local run of the
//
//
// shape to recognise: a whole-graph failure still reports every denominator,
// so it reads like a port that is wrong everywhere instead of a port that
// never ran.
//
// So dat/ now lives INSIDE the module graph (js/dat_bundle.js, generated by
//
// -------------------------------------------------------------------------
// Diffed nethack-c/dat against nethack-c-v5/upstream/dat, then counted the
//
// 21 dat files differ between the trees.  NINE of them differ ONLY in a
// version banner or a comment line — `# NetHack 3.7` -> `# NetHack 5.0`,
// `-- 3.7.0: minend changed...` -> `-- 5.0.0: ...` — in files whose readers
// drop comments (makedefs' `#` lines; Lua's `--`).  Those nine are inert and
// are deliberately NOT listed below: GENFILES, data.base, dungeon.lua,
// engrave.txt, epitaph.txt, hellfill.lua, luahelper, minetn-1.lua, tribute.
//
// The other TWELVE differ in content, and are the list.
//
// asks only for history (vendored 5.0) and help/hh/license/optmenu/usagehlp
// (byte-identical).  js/data_base.js reads data.base (banner-only diff).
// every name it asks for is a file the two trees agree on.
//
// So NOT ONE of the twelve content-differing files is read by the public 44,
// keeping: the loader is not dead code waiting to be admitted, it runs on a
// the first recording that descends into Sokoban would silently desync the
// RNG on arrival.
//
// A NOTE ON MEASURING THIS, because two attempts were wrong before one was
// right.  Patching `fs.readFileSync` from a NODE_OPTIONS=--import module DOES
// catch js/dispfile.js's reads but SILENTLY MISSES js/sp_lev.js's.  The 2026
// -08-13 numbers came from an appendFileSync counter written into the function
// point the port had by then, which is exact for the same reason.

import { DAT } from './dat_bundle.js';
export { V5_DIVERGENT } from './dat_divergent.js';
import { V5_DIVERGENT } from './dat_divergent.js';

/** True when dat/<fname> is in the bundle and can be served. */
export function dat_exists(fname) {
    return DAT.has(fname);
}

/**
 * The contents of dat/<fname> as a string, or null when the port does not
 * carry that file.
 *
 * null is C's `if (!f) { if (complain) pline("Cannot open \"%s\".") }` arm and
 * every caller already has one.  The THROW is a different thing and must not
 * be laundered into it: it means the name is one 3.7 and 5.0 disagree on and
 * nobody has vendored the 5.0 bytes, so serving anything at all would be
 * serving the wrong game.
 */
export function dat_content(fname) {
    const text = DAT.get(fname);
    if (text !== undefined)
        return text;
    if (V5_DIVERGENT.has(fname))
        throw new Error(
            `dat/${fname} differs between NetHack 3.7 and 5.0 and has not been `
            + `vendored: nethack-c/dat holds the 3.7 content and the contest scores `
            + `5.0.  Copy nethack-c-v5/upstream/dat/${fname} to js/dat/${fname}, `
            + `remove it from V5_DIVERGENT, and regenerate js/dat_bundle.js.`);
    return null;
}
