// js/mdlib.js
// JavaScript port of nethack-c/src/mdlib.c

import { DEV_RANDOM } from './platform_identity.js';

// SFCTOOL_BIT is defined in nethack-c/include/global.h:578
const SFCTOOL_BIT = 1n << 30n;

/**
 * md_ignored_features()
 * Returns bitmask of features that should be ignored.
 * C source: nethack-c/src/mdlib.c:235-242
 */
export function md_ignored_features() {
    return (0n
            | (1n << 19n) /* SCORE_ON_BOTL */
            | SFCTOOL_BIT /* stored by SFCTOOL, not NetHack itself */
    );
}

/* mdlib.c:104 */
const opt_indent = "    ";
/* global.h COLNO */
const COLNO = 80;
/* mdlib.c:96 — MAXOPT 60 */
const MAXOPT = 60;


/* mdlib.c:1046 hacklib.c datamodel(0) — sizeof short/int/long/long long/ptr
 * on the reference build (macOS arm64/x86_64: 2/4/8/8/8). */
const DATAMODEL = "I32LP64";

/* mdlib.c:597 save_bones_compat_buf, as built by build_savebones_compat_string()
 * (mdlib.c:392-415).  On 5.0 the VERSION_COMPATIBILITY define is commented out
 * (patchlevel.h:62), so the whole #ifdef arm is compiled out and the else
 * branch is unconditional:
 *     "save and bones files accepted from version" + " %d.%d.%d only"
 * with VERSION_MAJOR/VERSION_MINOR/PATCHLEVEL = 5/0/0 (patchlevel.h:10-15). */
const save_bones_compat_buf =
    "save and bones files accepted from version 5.0.0 only";

/* mdlib.c:417-599 build_opts[], the entries this build's #ifdefs keep. */
const build_opts = [
    "color",                                                /* :424 */
    "data file compression",                                /* :434 COMPRESS */
    "deferred handling of hangup signal",                   /* :457 SAFERHANGUP */
    "insurance files for recovering from crashes",          /* :463 INSURANCE */
    "live logging support",                                 /* :466 LIVELOG */
    "log file",                                             /* :469 LOGFILE */
    "extended log file",                                    /* :472 XLOGFILE */
    "errors and warnings log file",                         /* :475 PANICLOG */
    "mail daemon",                                          /* :478 MAIL */
    "news file",                                            /* :487 NEWS */
    "internal pager used for viewing help files",           /* :504 UNIX+DLB */
    "pattern matching via :PATMATCH:",                      /* :508 (rt token) */
    "pseudo random numbers generated by ISAAC64",           /* :510 USE_ISAAC64 */
    "strong PRNG seed from " + DEV_RANDOM,                  /* :513 DEV_RANDOM */
    "restore saved games via menu",                         /* :527 SELECTSAVED */
    "screen clipping",                                      /* :533 CLIPPING */
    "shell command",                                        /* :553 SHELL */
    "traditional status display",                           /* :555 */
    "status via windowport with highlighting",              /* :557 STATUS_HILITES */
    "suspend command",                                      /* :562 SUSPEND */
    "terminal info library",                                /* :566 TERMINFO */
    "system configuration at run-time",                     /* :589 SYSCF */
    "show stack trace on error",                            /* :592 PANICTRACE */
    "launch browser to report issues",                      /* :595 CRASHREPORT */
    save_bones_compat_buf,                                  /* :597 */
    "and basic NetHack features",                           /* :598 */
];

/* mdlib.c:112-164 window_opts[] — only TTY_GRAPHICS is defined here.  `valid`
 * is what count_and_validate_winopts() (mdlib.c:601-623) sets; on a non-WIN32
 * build it unconditionally sets every entry valid and returns the count. */
const window_opts = [
    { id: "tty", name: "traditional text with optional line-drawing", valid: false },
];

/* mdlib.c:184-231 soundlib_opts[] — only soundlib_nosound survives this
 * build's #ifdefs.  count_and_validate_soundlibopts() (mdlib.c:626-637)
 * likewise marks every entry valid and returns the count. */
const soundlib_opts = [
    { text_id: "soundlib_nosound", valid: false },
];

/* mdlib.c:601-623 */
function count_and_validate_winopts() {
    let cnt = 0;
    for (let i = 0; i < window_opts.length; i++) {
        ++cnt;
        window_opts[i].valid = true;
    }
    return cnt;
}

/* mdlib.c:626-637 */
function count_and_validate_soundlibopts() {
    let cnt = 0;
    for (let i = 0; i < soundlib_opts.length; i++) {
        ++cnt;
        soundlib_opts[i].valid = true;
    }
    return cnt;
}

/* ── static state (mdlib.c:95-103) ──────────────────────────────────────── */
let idxopttext = 0;
let done_runtime_opt_init_once = 0;
let opttext = new Array(MAXOPT).fill(null);
/* mdlib.c:102 — the single scratch line every builder appends into */
let optbuf = "";

/* mdlib.c:98-101 STOREOPTTEXT */
function STOREOPTTEXT(line) {
    if (idxopttext < MAXOPT)
        opttext[idxopttext++] = line;
}

/**
 * opt_out_words()
 * C source: nethack-c/src/mdlib.c:640-666
 *
 * Emits `str`'s space-separated words into optbuf, breaking to a fresh
 * opt_indent-prefixed line whenever the next word would push the running
 * length past COLNO - 5.  `length` is C's in/out int; JS returns the updated
 * value rather than taking a pointer.
 *
 * Note the C quirk this preserves: the caller primes `length` with COLNO + 1
 * to force the first word onto a new line, which makes the very first call of
 * a section STOREOPTTEXT() the (empty) optbuf — that stored empty string is
 * why every section header in the window is followed by exactly one blank
 * opttext entry.
 */
function opt_out_words(str, length) {
    while (str.length) {
        const sp = str.indexOf(' ');
        const word = (sp >= 0) ? str.slice(0, sp) : str;
        if (length + word.length > COLNO - 5) {
            STOREOPTTEXT(optbuf);
            optbuf = opt_indent;
            length = opt_indent.length;
        } else {
            optbuf += " ";
            length++;
        }
        optbuf += word;
        length += word.length;
        str = str.slice(word.length + (sp >= 0 ? 1 : 0));
    }
    return length;
}

/**
 * build_options()
 * C source: nethack-c/src/mdlib.c:668-830
 */
function build_options() {
    let buf, length, winsyscnt, cnt = 0;
    const defwinsys = "tty";  /* DEFAULT_WINDOW_SYS */

    /* build_savebones_compat_string() — already folded into
     * save_bones_compat_buf above (it is build-constant). */
    STOREOPTTEXT(optbuf);
    /* NH_DEVEL_STATUS != NH_STATUS_RELEASED on this build ⇒ STATUS_ARG is
     * " [work-in-progress]"; the trailing "\n" is C's, and doextversion()
     * strips it with strip_newline(). */
    optbuf = `${opt_indent}NetHack version 3.7.0 [work-in-progress]\n`;
    STOREOPTTEXT(optbuf);
    optbuf = "Options compiled into this edition:";
    STOREOPTTEXT(optbuf);
    optbuf = "";
    length = COLNO + 1; /* force 1st item onto new line */
    buf = DATAMODEL + " data model,";
    length = opt_out_words(buf, length);
    for (let i = 0; i < build_opts.length; i++) {
        buf = build_opts[i] + ((i < build_opts.length - 1) ? "," : ".");
        length = opt_out_words(buf, length);
    }
    STOREOPTTEXT(optbuf);
    optbuf = "";
    winsyscnt = count_and_validate_winopts();
    STOREOPTTEXT(optbuf);
    optbuf = `Supported windowing system${(winsyscnt > 1) ? "s" : ""}:`;
    STOREOPTTEXT(optbuf);
    optbuf = "";
    length = COLNO + 1; /* force 1st item onto new line */

    for (let i = 0; i < window_opts.length; i++) {
        if (!window_opts[i].valid)
            continue;
        buf = `"${window_opts[i].id}"`;
        if (window_opts[i].name !== window_opts[i].id)
            buf += ` (${window_opts[i].name})`;
        /*
         * 1 : foo.
         * 2 : foo and bar,
         * 3+: for, bar, and quux,
         */
        buf += (winsyscnt === 1) ? "."          /* no 'default' */
               : (winsyscnt === 2 && cnt === 0) ? " and"
                 : (cnt === winsyscnt - 2) ? ", and"
                   : ",";
        length = opt_out_words(buf, length);
        cnt++;
    }
    if (cnt > 1) {
        buf = `with a default of "${defwinsys}".`;
        length = opt_out_words(buf, length);
    }

    cnt = 0;
    STOREOPTTEXT(optbuf);
    optbuf = "";
    let soundlibcnt = count_and_validate_soundlibopts();
    STOREOPTTEXT(optbuf);
    optbuf = `Supported soundlib${(soundlibcnt > 1) ? "s" : ""}:`;
    STOREOPTTEXT(optbuf);
    optbuf = "";
    length = COLNO + 1; /* force 1st item onto new line */

    /* USER_SOUNDS is not defined on this build (no "user sounds." trailer). */
    for (let i = 0; i < soundlib_opts.length; i++) {
        if (!soundlib_opts[i].valid)
            continue;
        let soundlib = soundlib_opts[i].text_id;
        if (soundlib.startsWith("soundlib_"))
            soundlib = soundlib.slice(9);
        buf = `"${soundlib}"`;
        buf += (soundlibcnt === 1 || cnt === soundlibcnt - 1)
               ? "."                            /* no 'with default' */
               : (soundlibcnt === 2 && cnt === 0) ? " and"
                 : (cnt === soundlibcnt - 2) ? ", and"
                   : ",";
        length = opt_out_words(buf, length);
        cnt++;
    }

    STOREOPTTEXT(optbuf);
    optbuf = "";

    /* mdlib.c:800-817 lua_info[] — ":TAG:" substitutions are deferred to the
     * caller (version.c insert_rtoption).  Copied verbatim, trailing spaces
     * and all. */
    const lua_info = [
        "", "NetHack 5.0.* uses the 'Lua' interpreter to process some data:", "",
        "    :LUACOPYRIGHT:", "",
        ("    \"Permission is hereby granted, free of charge,"
         + " to any person obtaining"),
        "     a copy of this software and associated documentation files (the ",
        "     \"Software\"), to deal in the Software without restriction including",
        "     without limitation the rights to use, copy, modify, merge, publish,",
        "     distribute, sublicense, and/or sell copies of the Software, and to ",
        "     permit persons to whom the Software is furnished to do so, subject to",
        "     the following conditions:",
        "     The above copyright notice and this permission notice shall be",
        "     included in all copies or substantial portions of the Software.\"",
    ];
    for (let i = 0; i < lua_info.length; ++i)
        STOREOPTTEXT(lua_info[i]);

    /* end with a blank line */
    STOREOPTTEXT("");
}

/**
 * runtime_info_init()
 * C source: nethack-c/src/mdlib.c:834-846
 */
export function runtime_info_init() {
    if (!done_runtime_opt_init_once) {
        done_runtime_opt_init_once = 1;
        /* build_savebones_compat_string(); make_version();
         * populate_nomakedefs(&version); — all build-constant here. */
        idxopttext = 0;
        build_options();
    }
}

/**
 * do_runtime_info()
 * C source: nethack-c/src/mdlib.c:848-861
 *
 * `rtcontext` is C's int* — an object with a `.value` field here, incremented
 * in place on every successful fetch.  Returns null at the end of the text,
 * which is doextversion()'s loop terminator.
 */
export function do_runtime_info(rtcontext) {
    let retval = null;

    if (!done_runtime_opt_init_once)
        runtime_info_init();
    if (idxopttext && rtcontext != null) {
        const idx = (typeof rtcontext === 'object') ? rtcontext.value : rtcontext;
        if (idx >= 0 && idx < MAXOPT) {
            retval = opttext[idx];
            if (typeof rtcontext === 'object')
                rtcontext.value += 1;
        }
    }
    return retval;
}

/**
 * release_runtime_info()
 * C source: nethack-c/src/mdlib.c:863-872
 */
export function release_runtime_info() {
    while (idxopttext > 0) {
        --idxopttext;
        opttext[idxopttext] = null;
    }
    done_runtime_opt_init_once = 0;
}
