// @ts-nocheck
// o_init_data.js — canonical object descriptions and names per shuffled class.
// AUTO-EXTRACTED from nethack-c/include/objects.h (the C reference, READ ONLY).
// These are CANONICAL (pre-shuffle) descriptions and the role-invariant object
// names — facts about the object table, NOT per-seed shuffle results.  The real
// shuffle in o_init.js permutes the descr indices using the live RNG; the
// resulting per-otyp appearance is stored in game._objDescriptions.
//
// Each SHUFFLED_RANGES entry: { base: <JS otyp of first item in range>,
//   names: [OBJ_NAME...], descrs: [OBJ_DESCR canonical...] } ordered by otyp.
// Order matches C objects.h enum order == JS otyp order within each range
// (verified: SCR_TELEPORTATION=323+10=333, SPE_FORCE_BOLT=366+10=376,
//  quarterstaff=18+61=79, cloak of magic resistance=146+2=148, SPEED_BOOTS=166).
// C ref: o_init.c shuffle_all() class set + obj_shuffle_range() sub-ranges.
export const SHUFFLED_RANGES = {
 "AMULET": {
  "base": 201,
  "names": [
   "amulet of ESP",
   "amulet of life saving",
   "amulet of strangulation",
   "amulet of restful sleep",
   "amulet versus poison",
   "amulet of change",
   "amulet of unchanging",
   "amulet of reflection",
   "amulet of magical breathing",
   "amulet of guarding",
   "amulet of flying"
  ],
  "descrs": [
   "circular",
   "spherical",
   "oval",
   "triangular",
   "pyramidal",
   "square",
   "concave",
   "hexagonal",
   "octagonal",
   "perforated",
   "cubical"
  ]
 },
 "POTION": {
  "base": 297,
  "names": [
   "gain ability",
   "restore ability",
   "confusion",
   "blindness",
   "paralysis",
   "speed",
   "levitation",
   "hallucination",
   "invisibility",
   "see invisible",
   "healing",
   "extra healing",
   "gain level",
   "enlightenment",
   "monster detection",
   "object detection",
   "gain energy",
   "sleeping",
   "full healing",
   "polymorph",
   "booze",
   "sickness",
   "fruit juice",
   "acid",
   "oil"
  ],
  "descrs": [
   "ruby",
   "pink",
   "orange",
   "yellow",
   "emerald",
   "dark green",
   "cyan",
   "sky blue",
   "brilliant blue",
   "magenta",
   "purple-red",
   "puce",
   "milky",
   "swirly",
   "bubbly",
   "smoky",
   "cloudy",
   "effervescent",
   "black",
   "golden",
   "brown",
   "fizzy",
   "dark",
   "white",
   "murky"
  ]
 },
 "RING": {
  "base": 173,
  "names": [
   "adornment",
   "gain strength",
   "gain constitution",
   "increase accuracy",
   "increase damage",
   "protection",
   "regeneration",
   "searching",
   "stealth",
   "sustain ability",
   "levitation",
   "hunger",
   "aggravate monster",
   "conflict",
   "warning",
   "poison resistance",
   "fire resistance",
   "cold resistance",
   "shock resistance",
   "free action",
   "slow digestion",
   "teleportation",
   "teleport control",
   "polymorph",
   "polymorph control",
   "invisibility",
   "see invisible",
   "protection from shape changers"
  ],
  "descrs": [
   "wooden",
   "granite",
   "opal",
   "clay",
   "coral",
   "black onyx",
   "moonstone",
   "tiger eye",
   "jade",
   "bronze",
   "agate",
   "topaz",
   "sapphire",
   "ruby",
   "diamond",
   "pearl",
   "iron",
   "brass",
   "copper",
   "twisted",
   "steel",
   "silver",
   "gold",
   "ivory",
   "emerald",
   "wire",
   "engagement",
   "shiny"
  ]
 },
 "SCROLL": {
  "base": 323,
  "names": [
   "enchant armor",
   "destroy armor",
   "confuse monster",
   "scare monster",
   "remove curse",
   "enchant weapon",
   "create monster",
   "taming",
   "genocide",
   "light",
   "teleportation",
   "gold detection",
   "food detection",
   "identify",
   "magic mapping",
   "amnesia",
   "fire",
   "earth",
   "punishment",
   "charging",
   "stinking cloud",
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null
  ],
  "descrs": [
   "ZELGO MER",
   "JUYED AWK YACC",
   "NR 9",
   "XIXAXA XOXAXA XUXAXA",
   "PRATYAVAYAH",
   "DAIYEN FOOELS",
   "LEP GEX VEN ZEA",
   "PRIRUTSENIE",
   "ELBIB YLOH",
   "VERR YED HORRE",
   "VENZAR BORGAVVE",
   "THARR",
   "YUM YUM",
   "KERNOD WEL",
   "ELAM EBOW",
   "DUAM XNAHT",
   "ANDOVA BEGARIN",
   "KIRJE",
   "VE FORBRYDERNE",
   "HACKEM MUCHE",
   "VELOX NEB",
   "FOOBIE BLETCH",
   "TEMOV",
   "GARVEN DEH",
   "READ ME",
   "ETAOIN SHRDLU",
   "LOREM IPSUM",
   "FNORD",
   "KO BATE",
   "ABRA KA DABRA",
   "ASHPD SODALG",
   "ZLORFIK",
   "GNIK SISI VLE",
   "HAPAX LEGOMENON",
   "EIRIS SAZUN IDISI",
   "PHOL ENDE WODAN",
   "GHOTI",
   "MAPIRO MAHAMA DIROMAT",
   "VAS CORP BET MANI",
   "XOR OTA",
   "STRC PRST SKRZ KRK"
  ]
 },
 "SPBOOK": {
  "base": 366,
  "names": [
   "dig",
   "magic missile",
   "fireball",
   "cone of cold",
   "sleep",
   "finger of death",
   "light",
   "detect monsters",
   "healing",
   "knock",
   "force bolt",
   "confuse monster",
   "cure blindness",
   "drain life",
   "slow monster",
   "wizard lock",
   "create monster",
   "detect food",
   "cause fear",
   "clairvoyance",
   "cure sickness",
   "charm monster",
   "haste self",
   "detect unseen",
   "levitation",
   "extra healing",
   "restore ability",
   "invisibility",
   "detect treasure",
   "remove curse",
   "magic mapping",
   "identify",
   "turn undead",
   "polymorph",
   "teleport away",
   "create familiar",
   "cancellation",
   "protection",
   "jumping",
   "stone to flesh",
   "chain lightning"
  ],
  "descrs": [
   "parchment",
   "vellum",
   "ragged",
   "dog eared",
   "mottled",
   "stained",
   "cloth",
   "leathery",
   "white",
   "pink",
   "red",
   "orange",
   "yellow",
   "velvet",
   "light green",
   "dark green",
   "turquoise",
   "cyan",
   "light blue",
   "dark blue",
   "indigo",
   "magenta",
   "purple",
   "violet",
   "tan",
   "plaid",
   "light brown",
   "dark brown",
   "gray",
   "wrinkled",
   "dusty",
   "bronze",
   "copper",
   "silver",
   "gold",
   "glittering",
   "shining",
   "dull",
   "thin",
   "thick",
   "checkered"
  ]
 },
 "WAND": {
  "base": 410,
  "names": [
   "light",
   "secret door detection",
   "enlightenment",
   "create monster",
   "wishing",
   "stasis",
   "nothing",
   "striking",
   "make invisible",
   "slow monster",
   "speed monster",
   "undead turning",
   "polymorph",
   "cancellation",
   "teleportation",
   "opening",
   "locking",
   "probing",
   "digging",
   "magic missile",
   "fire",
   "cold",
   "sleep",
   "death",
   "lightning",
   null,
   null,
   null
  ],
  "descrs": [
   "glass",
   "balsa",
   "crystal",
   "maple",
   "pine",
   "redwood",
   "oak",
   "ebony",
   "marble",
   "tin",
   "brass",
   "copper",
   "silver",
   "platinum",
   "iridium",
   "zinc",
   "aluminum",
   "uranium",
   "iron",
   "steel",
   "hexagonal",
   "short",
   "runed",
   "long",
   "curved",
   "forked",
   "spiked",
   "jeweled"
  ]
 },
 "VENOM": {
  "base": 479,
  "names": [
   "splash of blinding venom",
   "splash of acid venom"
  ],
  "descrs": [
   "splash of venom",
   "splash of venom"
  ]
 },
 "HELMET": {
  "base": 97,
  "names": [
   "helmet",
   "helm of caution",
   "helm of opposite alignment",
   "helm of telepathy"
  ],
  "descrs": [
   "plumed helmet",
   "etched helmet",
   "crested helmet",
   "visored helmet"
  ]
 },
 "GLOVES": {
  "base": 159,
  "names": [
   "leather gloves",
   "gauntlets of fumbling",
   "gauntlets of power",
   "gauntlets of dexterity"
  ],
  "descrs": [
   "old gloves",
   "padded gloves",
   "riding gloves",
   "fencing gloves"
  ]
 },
 "CLOAK": {
  "base": 146,
  "names": [
   "cloak of protection",
   "cloak of invisibility",
   "cloak of magic resistance",
   "cloak of displacement"
  ],
  "descrs": [
   "tattered cape",
   "opera cloak",
   "ornamental cope",
   "piece of cloth"
  ]
 },
 "BOOTS": {
  "base": 166,
  "names": [
   "speed boots",
   "water walking boots",
   "jumping boots",
   "elven boots",
   "kicking boots",
   "fumble boots",
   "levitation boots"
  ],
  "descrs": [
   "combat boots",
   "jungle boots",
   "hiking boots",
   "mud boots",
   "buckled boots",
   "riding boots",
   "snow boots"
  ]
 }
};

// Full WEAPON name+fixed-descr table (weapons are NOT shuffled; descr is fixed).
// base 18 = WEAPON_CLASS start; aligned with JS otyp numbering.
export const WEAPON_TABLE = {
 "base": 18,
 "names": [
  "arrow",
  "elven arrow",
  "orcish arrow",
  "silver arrow",
  "ya",
  "crossbow bolt",
  "dart",
  "shuriken",
  "boomerang",
  "spear",
  "elven spear",
  "orcish spear",
  "dwarvish spear",
  "silver spear",
  "javelin",
  "trident",
  "dagger",
  "elven dagger",
  "orcish dagger",
  "silver dagger",
  "athame",
  "scalpel",
  "knife",
  "stiletto",
  "worm tooth",
  "crysknife",
  "axe",
  "battle-axe",
  "short sword",
  "elven short sword",
  "orcish short sword",
  "dwarvish short sword",
  "scimitar",
  "silver saber",
  "broadsword",
  "elven broadsword",
  "long sword",
  "two-handed sword",
  "katana",
  "tsurugi",
  "runesword",
  "partisan",
  "ranseur",
  "spetum",
  "glaive",
  "halberd",
  "bardiche",
  "voulge",
  "fauchard",
  "guisarme",
  "bill-guisarme",
  "lucern hammer",
  "bec de corbin",
  "dwarvish mattock",
  "lance",
  "mace",
  "silver mace",
  "morning star",
  "war hammer",
  "club",
  "rubber hose",
  "quarterstaff",
  "aklys",
  "flail",
  "bullwhip",
  "bow",
  "elven bow",
  "orcish bow",
  "yumi",
  "sling",
  "crossbow"
 ],
 "descrs": [
  null,
  "runed arrow",
  "crude arrow",
  null,
  "bamboo arrow",
  null,
  null,
  "throwing star",
  null,
  null,
  "runed spear",
  "crude spear",
  "stout spear",
  null,
  "throwing spear",
  null,
  null,
  "runed dagger",
  "crude dagger",
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  "double-headed axe",
  null,
  "runed short sword",
  "crude short sword",
  "broad short sword",
  "curved sword",
  null,
  null,
  "runed broadsword",
  null,
  null,
  "samurai sword",
  "long samurai sword",
  "runed broadsword",
  "vulgar polearm",
  "hilted polearm",
  "forked polearm",
  "single-edged polearm",
  "angled poleaxe",
  "long poleaxe",
  "pole cleaver",
  "pole sickle",
  "pruning hook",
  "hooked polearm",
  "pronged polearm",
  "beaked polearm",
  "broad pick",
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  "staff",
  "thonged club",
  null,
  null,
  null,
  "runed bow",
  "crude bow",
  "long bow",
  null,
  null
 ]
};

// Per-spellbook spell-school + level metadata for the 41 shuffled spellbooks
// (otyp base 366).  C ref: objects.h SPELL(name,desc,sub,prob,delay,level,...).
// Used by skill_based_spellbook_id() (spell.c:863) to decide which books a
// wizard recognizes from skill.  oc_skill / oc_level are role-invariant facts.
export const SPBOOK_META = [{"sub":"P_MATTER_SPELL","level":5},{"sub":"P_ATTACK_SPELL","level":2},{"sub":"P_ATTACK_SPELL","level":4},{"sub":"P_ATTACK_SPELL","level":4},{"sub":"P_ENCHANTMENT_SPELL","level":3},{"sub":"P_ATTACK_SPELL","level":7},{"sub":"P_DIVINATION_SPELL","level":1},{"sub":"P_DIVINATION_SPELL","level":1},{"sub":"P_HEALING_SPELL","level":1},{"sub":"P_MATTER_SPELL","level":1},{"sub":"P_ATTACK_SPELL","level":1},{"sub":"P_ENCHANTMENT_SPELL","level":1},{"sub":"P_HEALING_SPELL","level":2},{"sub":"P_ATTACK_SPELL","level":2},{"sub":"P_ENCHANTMENT_SPELL","level":2},{"sub":"P_MATTER_SPELL","level":2},{"sub":"P_CLERIC_SPELL","level":2},{"sub":"P_DIVINATION_SPELL","level":2},{"sub":"P_ENCHANTMENT_SPELL","level":3},{"sub":"P_DIVINATION_SPELL","level":3},{"sub":"P_HEALING_SPELL","level":3},{"sub":"P_ENCHANTMENT_SPELL","level":5},{"sub":"P_ESCAPE_SPELL","level":3},{"sub":"P_DIVINATION_SPELL","level":3},{"sub":"P_ESCAPE_SPELL","level":4},{"sub":"P_HEALING_SPELL","level":3},{"sub":"P_HEALING_SPELL","level":4},{"sub":"P_ESCAPE_SPELL","level":4},{"sub":"P_DIVINATION_SPELL","level":4},{"sub":"P_CLERIC_SPELL","level":3},{"sub":"P_DIVINATION_SPELL","level":5},{"sub":"P_DIVINATION_SPELL","level":3},{"sub":"P_CLERIC_SPELL","level":6},{"sub":"P_MATTER_SPELL","level":6},{"sub":"P_ESCAPE_SPELL","level":6},{"sub":"P_CLERIC_SPELL","level":6},{"sub":"P_MATTER_SPELL","level":7},{"sub":"P_CLERIC_SPELL","level":1},{"sub":"P_ESCAPE_SPELL","level":1},{"sub":"P_HEALING_SPELL","level":3},{"sub":"P_ATTACK_SPELL","level":2}];

// Fixed (non-shuffled) descriptions for items whose description lies outside
// the shuffle range: POT_WATER, and the three books objects.h files under
// "books with fixed descriptions" (blank paper, novel, Book of the Dead).
// Populated directly into game._objDescriptions.  C ref: objects.h
// fixed-description OBJECT() entries; keyed by JS otyp.
//
// comment named the cause without acting on it ("the post-protection
// spheres"): objects.h:1413-1421 wraps SPE_FLAME_SPHERE ("canvas") and
// SPE_FREEZE_SPHERE ("hardcover") in `#if 0 /* DEFERRED */`, so those two rows
// are NOT in the object enum, and the generator that produced these literals
// counted them anyway.  The keys were right and the values were two rows late:
//     407 "canvas"    / "flame sphere"    ->  "plain"     / "blank paper"
//     408 "hardcover" / "freeze sphere"   ->  "paperback" / "novel"
//     409 "plain"     / "blank paper"     ->  "papyrus"   / "Book of the Dead"
//
// This file DISAGREED WITH THE PORT'S OWN EXTRACTED TABLES, which are correct:
// js/oc_name_data.js OC_NAME[407..409] read "blank paper"/"novel"/"Book of the
// Dead" and js/oc_descr_data.js OC_DESCR[407..409] read "plain"/"paperback"/
// "papyrus", matching objects.h in BOTH the 5.0 tree and the 3.7 one -- so this
// was never a 3.7-vs-5.0 drift, it was a generator that did not honour `#if 0`.
//
// after cancellation blanks the hero's two spellbooks, C's inventory reads
// "an uncursed plain spellbook" twice where this port read "an uncursed canvas
// spellbook".  RNG-free -- these are appearance strings, not draws.
export const FIXED_DESCRS = {"322":"clear","407":"plain","408":"paperback","409":"papyrus"};

// OBJ_NAME for the fixed-description items in FIXED_DESCRS (keyed by JS otyp).
export const FIXED_NAMES = {"322":"water","407":"blank paper","408":"novel","409":"Book of the Dead"};
