// @ts-nocheck
// optlist.js — the allopt[] option table.
// C ref: nethack-c/include/optlist.h — the NHOPTB/NHOPTC/NHOPTP/NHOPTO macro
// list that expands (under NHOPT_PARSE) into `struct allopt_t allopt[]`
// (options.c).  This file is that expansion, evaluated for the REFERENCE
//
// Each row is [name, opttyp, setwhere, skipflags, descr]:
//   opttyp    'B' BoolOpt | 'C' CompOpt (incl. the NHOPTP prefix options) |
//             'O' OthrOpt.
//   setwhere  enum optset_restrictions, minus its `set_` prefix.
//   skipflags comma-joined pre-evaluated build facts that C tests at run time
//             against data this port does not model:
//               'noaddr'  allopt[].addr == (boolean *) 0 — the option's
//                         variable does not exist in this build, so
//                         option_help()'s `!allopt[i].addr` arm skips it.
//               'nowc'    the option is an is_wc_option()/is_wc2_option()
//                         name whose window-capability bit is NOT in the tty
//                         port's tty_procs.wincap/wincap2, so wc_supported()/
//                         wc2_supported() return FALSE.  win/tty/ is not part
//                         of the read-only C reference in nethack-c/ (only
//                         dat/, include/ and src/ are present), so the bit
//                         sets cannot be read from source here; the marked
//                         set is exactly the wc_options[]/wc2_options[]
//                         (options.c:9494-9518) members absent from the
//                         reference build's own option_help output.
//   descr     allopt[].descr (the CompOpt/OthrOpt help text; C carries one for
//             booleans too and option_help never prints it).
//
// PREPROCESSOR RESOLUTION.  optlist.h guards many entries with #ifdef pairs
// whose two arms differ (a real `addr` + description vs `(boolean *) 0` +
// "(not applicable)").  The arms taken here are the ones a unix + tty build
// selects: ALTMETA, INSURANCE, TTY_GRAPHICS, NEWS, BACKWARD_COMPAT,
// CRASHREPORT, PREV_MSGS, STATUS_HILITES and SELECTSAVED defined; MICRO,
// AMIGA, MAC, MSDOS, DEBUG, SCORE_ON_BOTL, TIMED_DELAY (unixconf.h:115 leaves
// it commented out and MACOS — the pre-OSX Mac port macro — is not defined),
// TTY_TILES_ESCCODES and TTY_SOUND_ESCCODES undefined.  `#if 0` entries
// (large_font) are dropped.
//
// Consumers must apply C's own run-time filters (wizard mode, opttyp) rather
// than assuming this list is pre-filtered — see options.js option_help().
export const ALLOPT = [
    ["windowtype", 'C', 'gameview', "", "windowing system to use (should be specified first)"],
    ["playmode", 'C', 'gameview', "", "normal play, non-scoring explore mode, or debug mode"],
    ["name", 'C', 'gameview', "", "your character's name (e.g., name:Merlin-W)"],
    ["role", 'C', 'gameview', "", "your starting role (e.g., Barbarian, Valkyrie)"],
    ["race", 'C', 'gameview', "", "your starting race (e.g., Human, Elf)"],
    ["gender", 'C', 'gameview', "", "your starting gender (male or female)"],
    ["alignment", 'C', 'gameview', "", "your starting alignment (lawful, neutral, or chaotic)"],
    ["accessiblemsg", 'B', 'in_game', "", "add location information to messages"],
    ["acoustics", 'B', 'in_game', "", "can your character hear anything"],
    ["align_message", 'C', 'gameview', "nowc", "message window alignment"],
    ["align_status", 'C', 'gameview', "nowc", "status window alignment"],
    ["altkeyhandling", 'C', 'in_config', "", "(not applicable)"],
    ["altmeta", 'B', 'in_game', "", "treat \"ESC c\" as M-c (Meta+c, 8th bit set)"],
    ["armorstatus", 'B', 'in_game', "", "summarize currently worn armor in a status field"],
    ["ascii_map", 'B', 'in_game', "nowc", "show map as text"],
    ["autocompletions", 'O', 'in_game', "", "edit autocompletions"],
    ["autodescribe", 'B', 'in_game', "", "describe terrain under cursor"],
    ["autodig", 'B', 'in_game', "", "dig if moving and wielding a digging tool"],
    ["autoopen", 'B', 'in_game', "", "walking into a door attempts to open it"],
    ["autopickup", 'B', 'in_game', "", "automatically pick up objects"],
    ["autopickup exceptions", 'O', 'in_game', "", "edit autopickup exceptions"],
    ["autoquiver", 'B', 'in_game', "", "fill empty quiver automatically when firing"],
    ["autounlock", 'C', 'in_game', "", "action to take when encountering locked door or chest"],
    ["bgcolors", 'B', 'in_game', "", "use background color for some map hilighting"],
    ["bind keys", 'O', 'in_game', "", "edit key binds"],
    ["BIOS", 'B', 'in_config', "noaddr", ""],
    ["blind", 'B', 'in_config', "", "your character is permanently blind"],
    ["bones", 'B', 'in_config', "", "allow loading bones files"],
    ["boulder", 'C', 'in_game', "", "deprecated (use S_boulder in sym file instead)"],
    ["catname", 'C', 'gameview', "", "name of your starting pet if it is a kitten"],
    ["checkpoint", 'B', 'in_game', "", "save game state after each level change"],
    ["cmdassist", 'B', 'in_game', "", "give help for errors on direction input"],
    ["color", 'B', 'in_game', "", "use color in map"],
    ["confirm", 'B', 'in_game', "", "ask before hitting tame or peaceful monsters"],
    ["crash_email", 'C', 'in_game', "", "email address for reporting"],
    ["crash_name", 'C', 'in_game', "", "your name for reporting"],
    ["crash_urlmax", 'C', 'in_game', "", "length of longest url we can generate"],
    ["customcolors", 'B', 'in_game', "", "use custom colors in map"],
    ["customsymbols", 'B', 'in_game', "", "use custom utf8 symbols in map"],
    ["dark_room", 'B', 'in_game', "", "show floor outside line of sight differently"],
    ["deaf", 'B', 'in_config', "", "your character is permanently deaf"],
    ["DECgraphics", 'C', 'in_config', "", "load DECGraphics display symbols into symset"],
    ["debug_hunger", 'B', 'wiznofuz', "", "no hunger"],
    ["debug_mongen", 'B', 'wiznofuz', "", "no random monster generation"],
    ["debug_overwrite_stairs", 'B', 'wiznofuz', "", "level generation can overwrite stairs"],
    ["disclose", 'C', 'in_game', "", "the kinds of information to disclose at end of game"],
    ["dogname", 'C', 'gameview', "", "name of your starting pet if it is a little dog"],
    ["dropped_nopick", 'B', 'in_game', "", "don't autopickup dropped items"],
    ["dungeon", 'C', 'in_config', "", "list of symbols to use in drawing the dungeon map"],
    ["effects", 'C', 'in_config', "", "list of symbols to use in drawing special effects"],
    ["eight_bit_tty", 'B', 'in_game', "", "send 8-bit characters directly to terminal"],
    ["extmenu", 'B', 'in_game', "", "use menu for getting extended commands"],
    ["female", 'B', 'in_config', "", "deprecated; use gender:female"],
    ["fireassist", 'B', 'in_game', "", "fire-command tries to be helpful"],
    ["fixinv", 'B', 'in_game', "", "inventory items keep their letters"],
    ["font_map", 'C', 'gameview', "nowc", "font to use in the map window"],
    ["font_menu", 'C', 'gameview', "nowc", "font to use in menus"],
    ["font_message", 'C', 'gameview', "nowc", "font to use in the message window"],
    ["font_size_map", 'C', 'gameview', "nowc", "size of the map font"],
    ["font_size_menu", 'C', 'gameview', "nowc", "size of the menu font"],
    ["font_size_message", 'C', 'gameview', "nowc", "size of the message font"],
    ["font_size_status", 'C', 'gameview', "nowc", "size of the status font"],
    ["font_size_text", 'C', 'gameview', "nowc", "size of the text font"],
    ["font_status", 'C', 'gameview', "nowc", "font to use in status window"],
    ["font_text", 'C', 'gameview', "nowc", "font to use in text windows"],
    ["force_invmenu", 'B', 'in_game', "", "commands asking for inventory item show a menu"],
    ["fruit", 'C', 'in_game', "", "name of a fruit you enjoy eating"],
    ["fullscreen", 'B', 'in_config', "nowc", "toggle fullscreen"],
    ["glyph", 'C', 'in_game', "", "set representation of a glyph to a unicode value and color"],
    ["goldX", 'B', 'in_game', "", "classify gold as unknown or uncursed"],
    ["guicolor", 'B', 'in_game', "nowc", "use color for UI"],
    ["help", 'B', 'in_game', "", "show all available info when using whatis-command"],
    ["herecmd_menu", 'B', 'in_game', "", "show commands available in this location"],
    ["hilite_pet", 'B', 'in_game', "", "use highlight for pets"],
    ["hilite_pile", 'B', 'in_game', "", "highlight piles of items"],
    ["hilite_status", 'C', 'in_game', "", "a status highlighting rule (can occur multiple times)"],
    ["hitpointbar", 'B', 'in_game', "", "show colored bar for hit points"],
    ["horsename", 'C', 'gameview', "", "name of your starting pet if it is a pony"],
    ["IBMgraphics", 'C', 'in_config', "", "load IBMGraphics display symbols into symset"],
    ["idlecheckpoint", 'B', 'in_game', "", "update checkpoint file if input is idle for 10 seconds"],
    ["ignintr", 'B', 'in_game', "", "ignore interrupt signals"],
    ["implicit_uncursed", 'B', 'in_game', "", "omit \"uncursed\" from inventory"],
    ["legacy", 'B', 'in_config', "", "show introductory message"],
    ["lit_corridor", 'B', 'in_game', "", "show dark corridors as lit if in sight"],
    ["lootabc", 'B', 'in_game', "", "use a/b/c rather than o/i/c when looting"],
    ["mail", 'B', 'in_game', "", "enable the mail daemon"],
    ["map_mode", 'C', 'gameview', "nowc", "map display mode under Windows"],
    ["mention_decor", 'B', 'in_game', "", "give feedback when walking over interesting features"],
    ["mention_map", 'B', 'in_game', "", "give feedback when interesting map locations change"],
    ["mention_walls", 'B', 'in_game', "", "give feedback when walking into walls"],
    ["menu_deselect_all", 'C', 'in_config', "", "deselect all items in a menu"],
    ["menu_deselect_page", 'C', 'in_config', "", "deselect all items on this page of a menu"],
    ["menu_first_page", 'C', 'in_config', "", "jump to the first page in a menu"],
    ["menu_headings", 'C', 'in_game', "", "display style for menu headings"],
    ["menu_invert_all", 'C', 'in_config', "", "invert all items in a menu"],
    ["menu_invert_page", 'C', 'in_config', "", "invert all items on this page of a menu"],
    ["menu_last_page", 'C', 'in_config', "", "jump to the last page in a menu"],
    ["menu_next_page", 'C', 'in_config', "", "go to the next menu page"],
    ["menu_objsyms", 'C', 'in_game', "", "show object symbols in menus"],
    ["menu_overlay", 'B', 'in_game', "", "menus overlay and align to right"],
    ["menu_previous_page", 'C', 'in_config', "", "go to the previous menu page"],
    ["menu_search", 'C', 'in_config', "", "search for a menu item"],
    ["menu_select_all", 'C', 'in_config', "", "select all items in a menu"],
    ["menu_select_page", 'C', 'in_config', "", "select all items on this page of a menu"],
    ["menu_shift_left", 'C', 'in_config', "", "pan current menu page left"],
    ["menu_shift_right", 'C', 'in_config', "", "pan current menu page right"],
    ["menu_tab_sep", 'B', 'wizonly', "", "menu formatting"],
    ["menucolors", 'B', 'in_game', "", "use colors in menus"],
    ["menu colors", 'O', 'in_game', "", "change colors used in menus"],
    ["menuinvertmode", 'C', 'in_game', "", "experimental behavior of menu inverts"],
    ["menustyle", 'C', 'in_game', "", "user interface for object selection"],
    ["message types", 'O', 'in_game', "", "edit message types"],
    ["mon_movement", 'B', 'in_game', "", "message when hero sees monster movement"],
    ["monpolycontrol", 'B', 'wizonly', "", "control monster polymorphs"],
    ["montelecontrol", 'B', 'wizonly', "", "control monster teleport destinations"],
    ["monsters", 'C', 'in_config', "", "list of symbols to use for monsters"],
    ["mouse_support", 'C', 'in_game', "nowc", "game receives click info from mouse"],
    ["msg_window", 'C', 'in_game', "", "control of \"view previous message(s)\" (^P) behavior"],
    ["msghistory", 'C', 'gameview', "", "number of top line messages to save"],
    ["news", 'B', 'in_config', "", "show any news at game start"],
    ["nudist", 'B', 'in_config', "", "start your character without armor"],
    ["null", 'B', 'in_game', "", "allow nulls to be sent to terminal"],
    ["number_pad", 'C', 'in_game', "", "use the number pad for movement"],
    ["objects", 'C', 'in_config', "", "list of symbols to use for objects"],
    ["packorder", 'C', 'in_game', "", "the inventory order of the items in your pack"],
    ["paranoid_confirmation", 'C', 'in_game', "", "extra prompting in certain situations"],
    ["pauper", 'B', 'in_config', "", "start your character without any items"],
    ["perm_invent", 'B', 'in_game', "nowc", "show persistent inventory window"],
    ["perminv_mode", 'C', 'in_game', "nowc", "what to show in persistent inventory window"],
    ["petattr", 'C', 'in_game', "", "attributes for highlighting pets"],
    ["pettype", 'C', 'gameview', "", "your preferred initial pet type"],
    ["pickup_burden", 'C', 'in_game', "", "maximum burden picked up before prompt"],
    ["pickup_stolen", 'B', 'in_game', "", "autopickup stolen items"],
    ["pickup_thrown", 'B', 'in_game', "", "autopickup thrown items"],
    ["pickup_types", 'C', 'in_game', "", "types of objects to pick up automatically"],
    ["pile_limit", 'C', 'in_game', "", "threshold for \"there are many objects here\""],
    ["player_selection", 'C', 'gameview', "nowc", "choose character via dialog or prompts"],
    ["popup_dialog", 'B', 'in_game', "nowc", ""],
    ["preload_tiles", 'B', 'in_config', "nowc", ""],
    ["price_quotes", 'B', 'in_game', "", "display prices you have seen for unidentified objects"],
    ["pushweapon", 'B', 'in_game', "", "previous weapon goes to secondary slot"],
    ["query_menu", 'B', 'in_game', "", "use a menu for yes/no queries"],
    ["quick_farsight", 'B', 'in_game', "", "skip map browse when forced to looked at map"],
    ["rawio", 'B', 'in_config', "noaddr", ""],
    ["reroll", 'B', 'in_config', "", "allow rerolling of starting inventory and items"],
    ["rest_on_space", 'B', 'in_game', "", "space bar is bound to the rest-command"],
    ["roguesymset", 'C', 'in_game', "", "load a set of rogue display symbols from symbols file"],
    ["runmode", 'C', 'in_game', "", "display frequency when `running' or `travelling'"],
    ["safe_pet", 'B', 'in_game', "", "prevent you from hitting pets"],
    ["safe_wait", 'B', 'in_game', "", "prevent waiting next to hostiles"],
    ["sanity_check", 'B', 'wizonly', "", "perform data sanity checks"],
    ["scores", 'C', 'in_game', "", "the parts of the score list you wish to see"],
    ["scroll_amount", 'C', 'gameview', "nowc", "amount to scroll map when scroll_margin is reached"],
    ["scroll_margin", 'C', 'gameview', "nowc", "scroll map when this far from the edge"],
    ["selectsaved", 'B', 'in_config', "", ""],
    ["showdamage", 'B', 'in_game', "", "show damage hero takes in message line"],
    ["showexp", 'B', 'in_game', "", "show experience points in status line"],
    ["showrace", 'B', 'in_game', "", "show your character by race rather than role"],
    ["showscore", 'B', 'in_config', "noaddr", ""],
    ["showvers", 'B', 'in_game', "", "show version info on status line"],
    ["silent", 'B', 'in_game', "", "don't use terminal bell"],
    ["softkeyboard", 'B', 'in_config', "nowc", ""],
    ["sortdiscoveries", 'C', 'in_game', "", "preferred order when displaying discovered objects"],
    ["sortloot", 'C', 'in_game', "", "sort object selection lists by description"],
    ["sortpack", 'B', 'in_game', "", "group inventory items by type"],
    ["sortvanquished", 'C', 'in_game', "", "preferred order when displaying vanquished monsters"],
    ["soundlib", 'C', 'gameview', "", "soundlib interface to use (if any)"],
    ["sounds", 'B', 'in_game', "", "use sounds"],
    ["sparkle", 'B', 'in_game', "", "display sparkly effect when resisting magic"],
    ["spot_monsters", 'B', 'in_game', "", "message when hero spots a monster"],
    ["splash_screen", 'B', 'in_config', "nowc", ""],
    ["standout", 'B', 'in_game', "", "use standout for --more--"],
    ["status_updates", 'B', 'in_config', "", "allow the status lines to update"],
    ["status condition fields", 'O', 'in_game', "", "change status condition highlighting"],
    ["statushilites", 'C', 'in_game', "", "0=no status highlighting, N=show highlights for N turns"],
    ["status highlight rules", 'O', 'in_game', "", "change status line highlighting"],
    ["statuslines", 'C', 'in_game', "", "2 or 3 lines for status display"],
    ["suppress_alert", 'C', 'in_game', "", "suppress alerts about version-specific features"],
    ["symset", 'C', 'in_game', "", "load a set of display symbols from symbols file"],
    ["term_cols", 'C', 'in_config', "nowc", "number of columns"],
    ["term_rows", 'C', 'in_config', "nowc", "number of rows"],
    ["terrainstatus", 'B', 'in_game', "", "show hero's location as a status field"],
    ["tile_file", 'C', 'gameview', "nowc", "name of tile file"],
    ["tile_height", 'C', 'gameview', "nowc", "height of tiles"],
    ["tile_width", 'C', 'gameview', "nowc", "width of tiles"],
    ["tiled_map", 'B', 'in_game', "nowc", ""],
    ["time", 'B', 'in_game', "", "display game turns in status line"],
    ["timed_delay", 'B', 'in_config', "noaddr", ""],
    ["tips", 'B', 'in_game', "", "show some helpful tips during gameplay"],
    ["tombstone", 'B', 'in_game', "", "show tombstone when your character dies"],
    ["toptenwin", 'B', 'in_game', "", "show top scores in window"],
    ["traps", 'C', 'in_config', "", "list of symbols to use in drawing traps"],
    ["travel", 'B', 'in_game', "", "enable traveling via mouse click"],
    ["travel_debug", 'B', 'wizonly', "noaddr", ""],
    ["tutorial", 'B', 'in_config', "", "ask if you want the tutorial"],
    ["use_darkgray", 'B', 'in_config', "", "use bold black color instead of blue"],
    ["use_inverse", 'B', 'in_game', "", "display detected monsters in inverse"],
    ["use_truecolor", 'B', 'in_config', "", ""],
    ["vary_msgcount", 'C', 'gameview', "nowc", "show more old messages at a time"],
    ["verbose", 'B', 'in_game', "", ""],
    ["versinfo", 'C', 'in_game', "", "extra information for 'showvers'"],
    ["voices", 'B', 'gameview', "", ""],
    ["vt_tiledata", 'B', 'in_config', "noaddr", ""],
    ["vt_sounddata", 'B', 'in_config', "noaddr", ""],
    ["warnings", 'C', 'in_config', "", "display characters for warnings"],
    ["weaponstatus", 'B', 'in_game', "", "show currently wielded weapon in a status field"],
    ["whatis_coord", 'C', 'in_game', "", "show coordinates when auto-describing cursor position"],
    ["whatis_filter", 'C', 'in_game', "", "filter coordinate locations when targeting next or previous"],
    ["whatis_menu", 'B', 'in_game', "", "show menu when getting a map location"],
    ["whatis_moveskip", 'B', 'in_game', "", "skip same glyph when getting map location"],
    ["windowborders", 'C', 'in_game', "nowc", "0 (off), 1 (on), 2 (auto)"],
    ["windowcolors", 'C', 'gameview', "nowc", "the foreground/background colors of windows"],
    ["wizmgender", 'B', 'wizonly', "", ""],
    ["wizweight", 'B', 'wizonly', "", ""],
    ["wraptext", 'B', 'in_game', "nowc", ""],
    ["cond_", 'C', 'hidden', "", "prefix for cond_ options"],
    ["font", 'C', 'hidden', "", "prefix for font options"],
];
